Add authentification backend
WildCodeSchool/p3-g4-sept21-lille-eazyapp-backend pull request #3
Opened 2022-01-11 16:02 UTC by HeloiseFerla

2022-01-11 16:08 UTC, Quentin-Macquart approved these changes, later dismissed

2022-01-11 16:08 UTC, Quentin-Macquart commented
Great job !

2022-01-12 10:00 UTC, Hacene010 requested changes
Dead code !

2022-01-12 10:00 UTC, Hacene010 commented on routes/auth.js
> +// router.post('/signup', async (req, res) => {
dead code ???

2022-01-12 13:30 UTC, Quentin-Macquart approved these changes

2022-01-12 14:02 UTC, Hacene010 approved these changes

2022-01-12 14:06 UTC, merged